//
//  RecipeModel.swift
//  GreenApple
//
//  Created by Can Arda on 27.02.26.
//

import Foundation

// MARK: - Recipe Category
enum RecipeCategory: String, CaseIterable, Identifiable {
    case all = "All"
    case breakfast = "Breakfast"
    case lunch = "Lunch"
    case dinner = "Dinner"
    case dessert = "Dessert"
    case snack = "Snack"
    case soup = "Soup"
    
    var id: String { rawValue }
    
    var icon: String {
        switch self {
        case .all: return "square.grid.2x2.fill"
        case .breakfast: return "sunrise.fill"
        case .lunch: return "sun.max.fill"
        case .dinner: return "moon.stars.fill"
        case .dessert: return "birthday.cake.fill"
        case .snack: return "leaf.fill"
        case .soup: return "flame.fill"
        }
    }
}

// MARK: - Difficulty
enum Difficulty: String, Codable {
    case easy = "Easy"
    case medium = "Medium"
    case hard = "Hard"
    
    var color: String {
        switch self {
        case .easy: return "AppGreen"
        case .medium: return "AppOrange"
        case .hard: return "red"
        }
    }
}

// MARK: - Ingredient
struct Ingredient: Identifiable, Codable {
    let id: UUID
    let name: String
    let amount: String
    let unit: String
}

// MARK: - Review
struct Review: Identifiable, Codable {
    let id: UUID
    let authorName: String
    let authorAvatar: String
    let rating: Int
    let comment: String
    let imageName: String?
    let date: Date
}

// MARK: - Recipe
struct Recipe: Identifiable, Codable {
    let id: UUID
    let name: String
    let description: String
    let category: String
    let imageName: String
    let prepTime: Int
    let cookTime: Int
    let servings: Int
    let calories: Int
    let difficulty: Difficulty
    let ingredients: [Ingredient]
    let steps: [String]
    var reviews: [Review]
    var isFavorite: Bool
    
    var recipeCategory: RecipeCategory {
        RecipeCategory(rawValue: category) ?? .all
    }
    var totalTime: Int { prepTime + cookTime }
    
    var formattedTotalTime: String {
        if totalTime >= 60 {
            let hours = totalTime / 60
            let mins = totalTime % 60
            return mins > 0 ? "\(hours)h \(mins)m" : "\(hours)h"
        }
        return "\(totalTime)m"
    }
    
    var averageRating: Double {
        guard !reviews.isEmpty else { return 0 }
        return Double(reviews.reduce(0) { $0 + $1.rating }) / Double(reviews.count)
    }
}

// MARK: - Sample Data
extension Recipe {
    static let sampleRecipes: [Recipe] = [
        // BREAKFAST
        Recipe(id: UUID(), name: "Avocado Toast", description: "Creamy avocado on toasted sourdough with poached eggs and chili flakes.", category: "Breakfast", imageName: "https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?w=400&q=80", prepTime: 5, cookTime: 10, servings: 2, calories: 320, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Sourdough bread", amount: "2", unit: "slices"), Ingredient(id: UUID(), name: "Avocado", amount: "1", unit: "large"), Ingredient(id: UUID(), name: "Eggs", amount: "2", unit: "pcs"), Ingredient(id: UUID(), name: "Lemon juice", amount: "1", unit: "tsp"), Ingredient(id: UUID(), name: "Chili flakes", amount: "1", unit: "pinch")], steps: ["Toast the sourdough bread until golden.", "Mash avocado with lemon juice, salt and pepper.", "Poach eggs in simmering water for 3 minutes.", "Spread avocado on toast, top with poached egg.", "Sprinkle chili flakes and serve."], reviews: [Review(id: UUID(), authorName: "Sarah M.", authorAvatar: "person.circle.fill", rating: 5, comment: "Perfect breakfast!", imageName: nil, date: Date())], isFavorite: false),

        Recipe(id: UUID(), name: "Banana Pancakes", description: "Fluffy banana pancakes perfect for a lazy weekend morning.", category: "Breakfast", imageName: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&q=80", prepTime: 10, cookTime: 15, servings: 3, calories: 340, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Ripe bananas", amount: "2", unit: "pcs"), Ingredient(id: UUID(), name: "Eggs", amount: "2", unit: "pcs"), Ingredient(id: UUID(), name: "Flour", amount: "150", unit: "g"), Ingredient(id: UUID(), name: "Milk", amount: "200", unit: "ml"), Ingredient(id: UUID(), name: "Baking powder", amount: "1", unit: "tsp")], steps: ["Mash bananas until smooth.", "Add eggs and milk, whisk together.", "Fold in flour and baking powder.", "Cook on medium heat 2 min each side.", "Serve with maple syrup."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Overnight Oats", description: "Creamy oats soaked overnight with chia seeds, berries and honey.", category: "Breakfast", imageName: "https://images.unsplash.com/photo-1495214783159-3503fd1b572d?w=400&q=80", prepTime: 10, cookTime: 0, servings: 1, calories: 380, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Rolled oats", amount: "80", unit: "g"), Ingredient(id: UUID(), name: "Milk", amount: "200", unit: "ml"), Ingredient(id: UUID(), name: "Chia seeds", amount: "1", unit: "tbsp"), Ingredient(id: UUID(), name: "Honey", amount: "1", unit: "tbsp"), Ingredient(id: UUID(), name: "Mixed berries", amount: "100", unit: "g")], steps: ["Combine oats, milk and chia seeds in a jar.", "Stir in honey and mix well.", "Refrigerate overnight.", "Top with fresh berries and serve cold."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Eggs Benedict", description: "Classic brunch dish with poached eggs, Canadian bacon and hollandaise sauce.", category: "Breakfast", imageName: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=400&q=80", prepTime: 15, cookTime: 20, servings: 2, calories: 480, difficulty: .hard, ingredients: [Ingredient(id: UUID(), name: "English muffins", amount: "2", unit: "pcs"), Ingredient(id: UUID(), name: "Eggs", amount: "4", unit: "pcs"), Ingredient(id: UUID(), name: "Canadian bacon", amount: "4", unit: "slices"), Ingredient(id: UUID(), name: "Butter", amount: "100", unit: "g"), Ingredient(id: UUID(), name: "Egg yolks", amount: "3", unit: "pcs"), Ingredient(id: UUID(), name: "Lemon juice", amount: "2", unit: "tbsp")], steps: ["Make hollandaise: whisk yolks with lemon juice over double boiler.", "Slowly add melted butter, whisking constantly.", "Toast English muffins, warm bacon.", "Poach eggs in simmering water.", "Assemble: muffin, bacon, egg, hollandaise."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Greek Yogurt Parfait", description: "Layered yogurt with granola, fresh fruits and a drizzle of honey.", category: "Breakfast", imageName: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80", prepTime: 5, cookTime: 0, servings: 1, calories: 290, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Greek yogurt", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Granola", amount: "50", unit: "g"), Ingredient(id: UUID(), name: "Strawberries", amount: "5", unit: "pcs"), Ingredient(id: UUID(), name: "Blueberries", amount: "50", unit: "g"), Ingredient(id: UUID(), name: "Honey", amount: "1", unit: "tbsp")], steps: ["Spoon half the yogurt into a glass.", "Add a layer of granola.", "Top with mixed berries.", "Repeat layers and drizzle with honey."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "French Toast", description: "Golden brioche slices soaked in vanilla custard, served with berries.", category: "Breakfast", imageName: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=400&q=80", prepTime: 10, cookTime: 10, servings: 2, calories: 420, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Brioche bread", amount: "4", unit: "slices"), Ingredient(id: UUID(), name: "Eggs", amount: "2", unit: "pcs"), Ingredient(id: UUID(), name: "Milk", amount: "100", unit: "ml"), Ingredient(id: UUID(), name: "Vanilla extract", amount: "1", unit: "tsp"), Ingredient(id: UUID(), name: "Cinnamon", amount: "1", unit: "tsp"), Ingredient(id: UUID(), name: "Butter", amount: "20", unit: "g")], steps: ["Whisk eggs, milk, vanilla and cinnamon.", "Dip bread slices in egg mixture.", "Cook in buttered pan until golden.", "Serve with powdered sugar and berries."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Smoothie Bowl", description: "Thick acai smoothie base topped with fruits, seeds and coconut flakes.", category: "Breakfast", imageName: "https://images.unsplash.com/photo-1501959915551-4e8d30928317?w=400&q=80", prepTime: 10, cookTime: 0, servings: 1, calories: 310, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Frozen acai", amount: "100", unit: "g"), Ingredient(id: UUID(), name: "Frozen banana", amount: "1", unit: "pcs"), Ingredient(id: UUID(), name: "Almond milk", amount: "50", unit: "ml"), Ingredient(id: UUID(), name: "Granola", amount: "30", unit: "g"), Ingredient(id: UUID(), name: "Fresh fruits", amount: "100", unit: "g")], steps: ["Blend acai, banana and almond milk until thick.", "Pour into a bowl.", "Top with granola, fruits and seeds.", "Serve immediately."], reviews: [], isFavorite: false),

        // LUNCH
        Recipe(id: UUID(), name: "Greek Salad", description: "Fresh Mediterranean salad with tomatoes, cucumbers, olives and feta cheese.", category: "Lunch", imageName: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80", prepTime: 15, cookTime: 0, servings: 2, calories: 220, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Tomatoes", amount: "3", unit: "large"), Ingredient(id: UUID(), name: "Cucumber", amount: "1", unit: "large"), Ingredient(id: UUID(), name: "Red onion", amount: "1/2", unit: "pcs"), Ingredient(id: UUID(), name: "Kalamata olives", amount: "100", unit: "g"), Ingredient(id: UUID(), name: "Feta cheese", amount: "150", unit: "g"), Ingredient(id: UUID(), name: "Olive oil", amount: "3", unit: "tbsp")], steps: ["Chop tomatoes, cucumber and red onion.", "Add olives and crumbled feta cheese.", "Drizzle with olive oil and season.", "Toss gently and serve fresh."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Chicken Caesar Wrap", description: "Grilled chicken, romaine lettuce and Caesar dressing wrapped in a tortilla.", category: "Lunch", imageName: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&q=80", prepTime: 15, cookTime: 10, servings: 2, calories: 440, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Chicken breast", amount: "300", unit: "g"), Ingredient(id: UUID(), name: "Tortilla wraps", amount: "2", unit: "pcs"), Ingredient(id: UUID(), name: "Romaine lettuce", amount: "100", unit: "g"), Ingredient(id: UUID(), name: "Caesar dressing", amount: "3", unit: "tbsp"), Ingredient(id: UUID(), name: "Parmesan", amount: "30", unit: "g"), Ingredient(id: UUID(), name: "Croutons", amount: "30", unit: "g")], steps: ["Season and grill chicken breast.", "Slice chicken into strips.", "Toss lettuce with Caesar dressing.", "Fill tortilla with lettuce, chicken, parmesan.", "Roll tightly and serve."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Caprese Sandwich", description: "Fresh mozzarella, tomatoes and basil on crusty ciabatta with pesto.", category: "Lunch", imageName: "https://images.unsplash.com/photo-1550507992-eb63ffee0847?w=400&q=80", prepTime: 10, cookTime: 0, servings: 2, calories: 390, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Ciabatta bread", amount: "1", unit: "loaf"), Ingredient(id: UUID(), name: "Fresh mozzarella", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Tomatoes", amount: "2", unit: "large"), Ingredient(id: UUID(), name: "Fresh basil", amount: "handful", unit: ""), Ingredient(id: UUID(), name: "Pesto", amount: "3", unit: "tbsp"), Ingredient(id: UUID(), name: "Olive oil", amount: "2", unit: "tbsp")], steps: ["Slice ciabatta in half lengthwise.", "Spread pesto on both halves.", "Layer mozzarella and tomato slices.", "Add fresh basil leaves.", "Drizzle with olive oil and close sandwich."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Quinoa Buddha Bowl", description: "Nutritious bowl with quinoa, roasted veggies, chickpeas and tahini dressing.", category: "Lunch", imageName: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&q=80", prepTime: 20, cookTime: 25, servings: 2, calories: 460, difficulty: .medium, ingredients: [Ingredient(id: UUID(), name: "Quinoa", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Chickpeas", amount: "400", unit: "g"), Ingredient(id: UUID(), name: "Sweet potato", amount: "2", unit: "pcs"), Ingredient(id: UUID(), name: "Tahini", amount: "3", unit: "tbsp"), Ingredient(id: UUID(), name: "Lemon juice", amount: "2", unit: "tbsp"), Ingredient(id: UUID(), name: "Kale", amount: "100", unit: "g")], steps: ["Cook quinoa according to package instructions.", "Roast chickpeas and sweet potato at 200°C.", "Make tahini dressing with lemon and water.", "Assemble bowl with all ingredients.", "Drizzle dressing and serve."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Tuna Nicoise Salad", description: "Classic French salad with tuna, green beans, eggs and olives.", category: "Lunch", imageName: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80", prepTime: 20, cookTime: 15, servings: 2, calories: 380, difficulty: .medium, ingredients: [Ingredient(id: UUID(), name: "Tuna steak", amount: "300", unit: "g"), Ingredient(id: UUID(), name: "Green beans", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Eggs", amount: "2", unit: "pcs"), Ingredient(id: UUID(), name: "Cherry tomatoes", amount: "150", unit: "g"), Ingredient(id: UUID(), name: "Black olives", amount: "80", unit: "g"), Ingredient(id: UUID(), name: "Dijon mustard", amount: "1", unit: "tbsp")], steps: ["Sear tuna steak 2 min each side.", "Blanch green beans in boiling water.", "Hard boil eggs, then halve.", "Arrange all ingredients on platter.", "Drizzle with mustard vinaigrette."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Mushroom Risotto", description: "Creamy Italian risotto with mixed mushrooms, parmesan and fresh thyme.", category: "Lunch", imageName: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400&q=80", prepTime: 10, cookTime: 35, servings: 4, calories: 520, difficulty: .hard, ingredients: [Ingredient(id: UUID(), name: "Arborio rice", amount: "300", unit: "g"), Ingredient(id: UUID(), name: "Mixed mushrooms", amount: "400", unit: "g"), Ingredient(id: UUID(), name: "Vegetable stock", amount: "1", unit: "L"), Ingredient(id: UUID(), name: "Parmesan", amount: "80", unit: "g"), Ingredient(id: UUID(), name: "White wine", amount: "150", unit: "ml"), Ingredient(id: UUID(), name: "Shallots", amount: "2", unit: "pcs")], steps: ["Sauté shallots and mushrooms in butter.", "Add rice, toast for 2 minutes.", "Pour in wine, stir until absorbed.", "Add warm stock ladle by ladle.", "Stir continuously for 25 minutes.", "Finish with parmesan and butter."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Falafel Pita", description: "Crispy homemade falafel in warm pita with tzatziki and fresh vegetables.", category: "Lunch", imageName: "https://images.unsplash.com/photo-1593001872095-7d5b3868fb1d?w=400&q=80", prepTime: 30, cookTime: 20, servings: 4, calories: 410, difficulty: .medium, ingredients: [Ingredient(id: UUID(), name: "Chickpeas", amount: "400", unit: "g"), Ingredient(id: UUID(), name: "Pita bread", amount: "4", unit: "pcs"), Ingredient(id: UUID(), name: "Garlic", amount: "3", unit: "cloves"), Ingredient(id: UUID(), name: "Cumin", amount: "2", unit: "tsp"), Ingredient(id: UUID(), name: "Fresh parsley", amount: "handful", unit: ""), Ingredient(id: UUID(), name: "Tzatziki", amount: "100", unit: "g")], steps: ["Blend chickpeas, garlic, cumin and parsley.", "Form into small balls.", "Fry in oil until golden and crispy.", "Warm pita bread.", "Fill with falafel, tzatziki and vegetables."], reviews: [], isFavorite: false),

        // DINNER
        Recipe(id: UUID(), name: "Spaghetti Carbonara", description: "Classic Italian pasta with crispy pancetta, eggs, and Pecorino Romano.", category: "Dinner", imageName: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400&q=80", prepTime: 10, cookTime: 20, servings: 4, calories: 580, difficulty: .medium, ingredients: [Ingredient(id: UUID(), name: "Spaghetti", amount: "400", unit: "g"), Ingredient(id: UUID(), name: "Pancetta", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Eggs", amount: "4", unit: "pcs"), Ingredient(id: UUID(), name: "Pecorino Romano", amount: "100", unit: "g"), Ingredient(id: UUID(), name: "Black pepper", amount: "2", unit: "tsp")], steps: ["Cook spaghetti until al dente.", "Fry pancetta until crispy.", "Whisk eggs with Pecorino and pepper.", "Remove pan from heat, add drained pasta.", "Pour egg mixture, toss quickly.", "Serve with extra cheese."], reviews: [], isFavorite: true),

        Recipe(id: UUID(), name: "Beef Tacos", description: "Seasoned ground beef tacos with fresh salsa, guacamole and sour cream.", category: "Dinner", imageName: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&q=80", prepTime: 15, cookTime: 15, servings: 4, calories: 520, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Ground beef", amount: "500", unit: "g"), Ingredient(id: UUID(), name: "Taco shells", amount: "8", unit: "pcs"), Ingredient(id: UUID(), name: "Taco seasoning", amount: "2", unit: "tbsp"), Ingredient(id: UUID(), name: "Salsa", amount: "100", unit: "g"), Ingredient(id: UUID(), name: "Guacamole", amount: "100", unit: "g"), Ingredient(id: UUID(), name: "Sour cream", amount: "50", unit: "g")], steps: ["Brown ground beef in a pan.", "Add taco seasoning and water.", "Simmer until sauce thickens.", "Warm taco shells.", "Fill with beef and toppings."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Salmon Teriyaki", description: "Glazed salmon fillet with homemade teriyaki sauce, served with steamed rice.", category: "Dinner", imageName: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&q=80", prepTime: 10, cookTime: 15, servings: 2, calories: 490, difficulty: .medium, ingredients: [Ingredient(id: UUID(), name: "Salmon fillet", amount: "400", unit: "g"), Ingredient(id: UUID(), name: "Soy sauce", amount: "60", unit: "ml"), Ingredient(id: UUID(), name: "Mirin", amount: "60", unit: "ml"), Ingredient(id: UUID(), name: "Sugar", amount: "2", unit: "tbsp"), Ingredient(id: UUID(), name: "Jasmine rice", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Sesame seeds", amount: "1", unit: "tbsp")], steps: ["Mix soy sauce, mirin and sugar for teriyaki.", "Marinate salmon for 10 minutes.", "Cook rice according to instructions.", "Pan-fry salmon 4 min each side.", "Glaze with teriyaki sauce.", "Serve with rice and sesame seeds."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Chicken Tikka Masala", description: "Tender chicken in a rich, creamy tomato-based curry sauce with aromatic spices.", category: "Dinner", imageName: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80", prepTime: 20, cookTime: 35, servings: 4, calories: 560, difficulty: .medium, ingredients: [Ingredient(id: UUID(), name: "Chicken breast", amount: "600", unit: "g"), Ingredient(id: UUID(), name: "Tomato passata", amount: "400", unit: "g"), Ingredient(id: UUID(), name: "Heavy cream", amount: "150", unit: "ml"), Ingredient(id: UUID(), name: "Garam masala", amount: "2", unit: "tbsp"), Ingredient(id: UUID(), name: "Garlic", amount: "4", unit: "cloves"), Ingredient(id: UUID(), name: "Ginger", amount: "2", unit: "cm")], steps: ["Marinate chicken in yogurt and spices.", "Grill chicken until slightly charred.", "Sauté onions, garlic and ginger.", "Add spices, then tomato sauce.", "Add cream and simmer 15 minutes.", "Add chicken and serve with naan."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Margherita Pizza", description: "Classic Neapolitan pizza with San Marzano tomatoes, fresh mozzarella and basil.", category: "Dinner", imageName: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80", prepTime: 90, cookTime: 12, servings: 4, calories: 640, difficulty: .hard, ingredients: [Ingredient(id: UUID(), name: "Pizza dough", amount: "500", unit: "g"), Ingredient(id: UUID(), name: "San Marzano tomatoes", amount: "400", unit: "g"), Ingredient(id: UUID(), name: "Fresh mozzarella", amount: "250", unit: "g"), Ingredient(id: UUID(), name: "Fresh basil", amount: "handful", unit: ""), Ingredient(id: UUID(), name: "Olive oil", amount: "2", unit: "tbsp"), Ingredient(id: UUID(), name: "Salt", amount: "to", unit: "taste")], steps: ["Let dough rest at room temperature.", "Stretch dough into 30cm circle.", "Spread crushed tomatoes on base.", "Top with torn mozzarella.", "Bake at 280°C for 10-12 minutes.", "Top with basil and olive oil."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Grilled Ribeye Steak", description: "Perfectly grilled ribeye with garlic butter, rosemary and crispy potatoes.", category: "Dinner", imageName: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&q=80", prepTime: 15, cookTime: 20, servings: 2, calories: 780, difficulty: .medium, ingredients: [Ingredient(id: UUID(), name: "Ribeye steak", amount: "600", unit: "g"), Ingredient(id: UUID(), name: "Garlic", amount: "4", unit: "cloves"), Ingredient(id: UUID(), name: "Rosemary", amount: "2", unit: "sprigs"), Ingredient(id: UUID(), name: "Butter", amount: "50", unit: "g"), Ingredient(id: UUID(), name: "Potatoes", amount: "400", unit: "g"), Ingredient(id: UUID(), name: "Sea salt", amount: "to", unit: "taste")], steps: ["Season steak generously with salt.", "Heat cast iron to smoking hot.", "Sear steak 3-4 min each side.", "Baste with garlic butter and rosemary.", "Rest for 5 minutes before slicing.", "Serve with crispy roasted potatoes."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Shrimp Scampi", description: "Succulent shrimp in garlic butter white wine sauce over linguine.", category: "Dinner", imageName: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400&q=80", prepTime: 10, cookTime: 15, servings: 4, calories: 490, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Large shrimp", amount: "500", unit: "g"), Ingredient(id: UUID(), name: "Linguine", amount: "400", unit: "g"), Ingredient(id: UUID(), name: "Garlic", amount: "5", unit: "cloves"), Ingredient(id: UUID(), name: "White wine", amount: "120", unit: "ml"), Ingredient(id: UUID(), name: "Butter", amount: "60", unit: "g"), Ingredient(id: UUID(), name: "Parsley", amount: "handful", unit: "")], steps: ["Cook linguine until al dente.", "Sauté garlic in butter.", "Add shrimp, cook 2 min each side.", "Deglaze with white wine.", "Toss with pasta and parsley.", "Serve immediately."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Beef Bourguignon", description: "Classic French beef stew braised in red wine with mushrooms and pearl onions.", category: "Dinner", imageName: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=400&q=80", prepTime: 30, cookTime: 150, servings: 6, calories: 620, difficulty: .hard, ingredients: [Ingredient(id: UUID(), name: "Beef chuck", amount: "1", unit: "kg"), Ingredient(id: UUID(), name: "Red wine", amount: "750", unit: "ml"), Ingredient(id: UUID(), name: "Mushrooms", amount: "300", unit: "g"), Ingredient(id: UUID(), name: "Pearl onions", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Bacon", amount: "150", unit: "g"), Ingredient(id: UUID(), name: "Beef stock", amount: "500", unit: "ml")], steps: ["Brown beef in batches.", "Sauté bacon, onions and mushrooms.", "Return beef, add wine and stock.", "Braise in oven at 160°C for 2.5 hours.", "Adjust seasoning.", "Serve with crusty bread or mashed potatoes."], reviews: [], isFavorite: false),

        // DESSERT
        Recipe(id: UUID(), name: "Chocolate Lava Cake", description: "Warm chocolate cake with a gooey molten center. Pure indulgence.", category: "Dessert", imageName: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&q=80", prepTime: 15, cookTime: 12, servings: 4, calories: 420, difficulty: .medium, ingredients: [Ingredient(id: UUID(), name: "Dark chocolate", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Butter", amount: "100", unit: "g"), Ingredient(id: UUID(), name: "Eggs", amount: "4", unit: "pcs"), Ingredient(id: UUID(), name: "Sugar", amount: "80", unit: "g"), Ingredient(id: UUID(), name: "Flour", amount: "40", unit: "g")], steps: ["Preheat oven to 200°C, grease ramekins.", "Melt chocolate and butter.", "Whisk eggs and sugar until pale.", "Fold in chocolate mixture.", "Add flour, pour into ramekins.", "Bake 10-12 min, serve immediately."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Tiramisu", description: "Classic Italian dessert with espresso-soaked ladyfingers and mascarpone cream.", category: "Dessert", imageName: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&q=80", prepTime: 30, cookTime: 0, servings: 8, calories: 380, difficulty: .medium, ingredients: [Ingredient(id: UUID(), name: "Ladyfingers", amount: "300", unit: "g"), Ingredient(id: UUID(), name: "Mascarpone", amount: "500", unit: "g"), Ingredient(id: UUID(), name: "Espresso", amount: "300", unit: "ml"), Ingredient(id: UUID(), name: "Eggs", amount: "4", unit: "pcs"), Ingredient(id: UUID(), name: "Sugar", amount: "100", unit: "g"), Ingredient(id: UUID(), name: "Cocoa powder", amount: "2", unit: "tbsp")], steps: ["Whisk egg yolks with sugar until pale.", "Fold in mascarpone.", "Whip cream, fold into mascarpone mixture.", "Dip ladyfingers in espresso.", "Layer fingers and cream in dish.", "Refrigerate 4 hours, dust with cocoa."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Crème Brûlée", description: "Rich vanilla custard with a perfectly caramelized sugar crust.", category: "Dessert", imageName: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=400&q=80", prepTime: 20, cookTime: 45, servings: 6, calories: 350, difficulty: .hard, ingredients: [Ingredient(id: UUID(), name: "Heavy cream", amount: "500", unit: "ml"), Ingredient(id: UUID(), name: "Egg yolks", amount: "6", unit: "pcs"), Ingredient(id: UUID(), name: "Sugar", amount: "100", unit: "g"), Ingredient(id: UUID(), name: "Vanilla bean", amount: "1", unit: "pcs"), Ingredient(id: UUID(), name: "Extra sugar", amount: "6", unit: "tbsp")], steps: ["Heat cream with vanilla bean.", "Whisk yolks with sugar.", "Combine, strain into ramekins.", "Bake in water bath at 160°C 40 min.", "Cool completely, refrigerate.", "Sprinkle sugar, torch to caramelize."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Apple Tart Tatin", description: "French upside-down caramelized apple tart with flaky puff pastry.", category: "Dessert", imageName: "https://images.unsplash.com/photo-1562007908-17c67e878c88?w=400&q=80", prepTime: 20, cookTime: 35, servings: 6, calories: 390, difficulty: .hard, ingredients: [Ingredient(id: UUID(), name: "Apples", amount: "6", unit: "pcs"), Ingredient(id: UUID(), name: "Puff pastry", amount: "300", unit: "g"), Ingredient(id: UUID(), name: "Butter", amount: "60", unit: "g"), Ingredient(id: UUID(), name: "Sugar", amount: "150", unit: "g"), Ingredient(id: UUID(), name: "Vanilla extract", amount: "1", unit: "tsp")], steps: ["Melt butter and sugar in oven-safe pan.", "Cook until amber caramel forms.", "Arrange apple halves on top.", "Cover with puff pastry.", "Bake at 200°C for 25 minutes.", "Flip onto plate immediately."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Chocolate Mousse", description: "Light and airy dark chocolate mousse with whipped cream.", category: "Dessert", imageName: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&q=80", prepTime: 20, cookTime: 0, servings: 4, calories: 320, difficulty: .medium, ingredients: [Ingredient(id: UUID(), name: "Dark chocolate", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Eggs", amount: "4", unit: "pcs"), Ingredient(id: UUID(), name: "Sugar", amount: "60", unit: "g"), Ingredient(id: UUID(), name: "Heavy cream", amount: "200", unit: "ml"), Ingredient(id: UUID(), name: "Butter", amount: "30", unit: "g")], steps: ["Melt chocolate with butter.", "Separate eggs, whisk yolks with sugar.", "Fold chocolate into yolk mixture.", "Whip cream to soft peaks.", "Whip egg whites to stiff peaks.", "Fold cream then whites into chocolate.", "Refrigerate 2 hours."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Strawberry Cheesecake", description: "Creamy New York style cheesecake with fresh strawberry compote.", category: "Dessert", imageName: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400&q=80", prepTime: 30, cookTime: 60, servings: 10, calories: 440, difficulty: .hard, ingredients: [Ingredient(id: UUID(), name: "Cream cheese", amount: "600", unit: "g"), Ingredient(id: UUID(), name: "Graham crackers", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Butter", amount: "80", unit: "g"), Ingredient(id: UUID(), name: "Sugar", amount: "150", unit: "g"), Ingredient(id: UUID(), name: "Eggs", amount: "3", unit: "pcs"), Ingredient(id: UUID(), name: "Strawberries", amount: "300", unit: "g")], steps: ["Crush crackers, mix with melted butter.", "Press into springform pan.", "Beat cream cheese with sugar.", "Add eggs one at a time.", "Bake at 160°C for 55 minutes.", "Cool, then top with strawberry compote."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Panna Cotta", description: "Silky Italian cream dessert with raspberry coulis and mint.", category: "Dessert", imageName: "https://images.unsplash.com/photo-1488477304112-4944851de03d?w=400&q=80", prepTime: 15, cookTime: 10, servings: 4, calories: 290, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Heavy cream", amount: "500", unit: "ml"), Ingredient(id: UUID(), name: "Gelatin", amount: "8", unit: "g"), Ingredient(id: UUID(), name: "Sugar", amount: "60", unit: "g"), Ingredient(id: UUID(), name: "Vanilla extract", amount: "1", unit: "tsp"), Ingredient(id: UUID(), name: "Raspberries", amount: "200", unit: "g")], steps: ["Bloom gelatin in cold water.", "Heat cream with sugar and vanilla.", "Dissolve gelatin in warm cream.", "Pour into ramekins.", "Refrigerate 4 hours.", "Serve with raspberry coulis."], reviews: [], isFavorite: false),

        // SNACK
        Recipe(id: UUID(), name: "Hummus & Pita", description: "Creamy homemade hummus with olive oil, paprika and warm pita triangles.", category: "Snack", imageName: "https://images.unsplash.com/photo-1541014741259-de529411b96a?w=400&q=80", prepTime: 10, cookTime: 0, servings: 4, calories: 280, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Chickpeas", amount: "400", unit: "g"), Ingredient(id: UUID(), name: "Tahini", amount: "60", unit: "g"), Ingredient(id: UUID(), name: "Lemon juice", amount: "3", unit: "tbsp"), Ingredient(id: UUID(), name: "Garlic", amount: "2", unit: "cloves"), Ingredient(id: UUID(), name: "Olive oil", amount: "3", unit: "tbsp"), Ingredient(id: UUID(), name: "Pita bread", amount: "4", unit: "pcs")], steps: ["Blend chickpeas, tahini, lemon and garlic.", "Add olive oil while blending.", "Add ice water for smoother texture.", "Season with salt and cumin.", "Drizzle with olive oil and paprika.", "Serve with warm pita."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Guacamole & Chips", description: "Fresh chunky guacamole with lime, cilantro and crispy tortilla chips.", category: "Snack", imageName: "https://images.unsplash.com/photo-1551887373-3c5bd224f6e2?w=400&q=80", prepTime: 10, cookTime: 0, servings: 4, calories: 240, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Avocados", amount: "3", unit: "ripe"), Ingredient(id: UUID(), name: "Lime juice", amount: "2", unit: "tbsp"), Ingredient(id: UUID(), name: "Red onion", amount: "1/4", unit: "pcs"), Ingredient(id: UUID(), name: "Cilantro", amount: "handful", unit: ""), Ingredient(id: UUID(), name: "Jalapeño", amount: "1", unit: "pcs"), Ingredient(id: UUID(), name: "Tortilla chips", amount: "200", unit: "g")], steps: ["Mash avocados with lime juice.", "Finely dice onion and jalapeño.", "Mix in cilantro and seasoning.", "Taste and adjust lime and salt.", "Serve immediately with chips."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Bruschetta", description: "Toasted bread topped with fresh tomatoes, garlic and basil.", category: "Snack", imageName: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=400&q=80", prepTime: 10, cookTime: 5, servings: 4, calories: 180, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Baguette", amount: "1", unit: "pcs"), Ingredient(id: UUID(), name: "Roma tomatoes", amount: "4", unit: "pcs"), Ingredient(id: UUID(), name: "Garlic", amount: "2", unit: "cloves"), Ingredient(id: UUID(), name: "Fresh basil", amount: "handful", unit: ""), Ingredient(id: UUID(), name: "Olive oil", amount: "3", unit: "tbsp"), Ingredient(id: UUID(), name: "Balsamic glaze", amount: "2", unit: "tbsp")], steps: ["Slice and toast baguette.", "Rub with garlic clove.", "Dice tomatoes, mix with basil.", "Season with olive oil and salt.", "Top bread with tomato mix.", "Drizzle with balsamic glaze."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Energy Balls", description: "No-bake oat and peanut butter energy balls with chocolate chips and honey.", category: "Snack", imageName: "https://images.unsplash.com/photo-1582819509237-d5b75f20ff7a?w=400&q=80", prepTime: 15, cookTime: 0, servings: 12, calories: 150, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Rolled oats", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Peanut butter", amount: "100", unit: "g"), Ingredient(id: UUID(), name: "Honey", amount: "60", unit: "ml"), Ingredient(id: UUID(), name: "Chocolate chips", amount: "60", unit: "g"), Ingredient(id: UUID(), name: "Chia seeds", amount: "2", unit: "tbsp"), Ingredient(id: UUID(), name: "Vanilla extract", amount: "1", unit: "tsp")], steps: ["Mix all ingredients in a bowl.", "Refrigerate dough for 30 minutes.", "Roll into 12 equal balls.", "Store in fridge for up to a week."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Caprese Skewers", description: "Mini skewers with mozzarella, cherry tomatoes and fresh basil.", category: "Snack", imageName: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=400&q=80", prepTime: 10, cookTime: 0, servings: 6, calories: 160, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Mini mozzarella", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Cherry tomatoes", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Fresh basil", amount: "20", unit: "leaves"), Ingredient(id: UUID(), name: "Olive oil", amount: "2", unit: "tbsp"), Ingredient(id: UUID(), name: "Balsamic glaze", amount: "2", unit: "tbsp")], steps: ["Thread tomato, basil and mozzarella on skewer.", "Arrange on serving plate.", "Drizzle with olive oil.", "Finish with balsamic glaze."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Nachos", description: "Loaded tortilla chips with melted cheese, jalapeños, sour cream and salsa.", category: "Snack", imageName: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=400&q=80", prepTime: 10, cookTime: 10, servings: 4, calories: 480, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Tortilla chips", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Cheddar cheese", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Jalapeños", amount: "50", unit: "g"), Ingredient(id: UUID(), name: "Sour cream", amount: "100", unit: "g"), Ingredient(id: UUID(), name: "Salsa", amount: "100", unit: "g"), Ingredient(id: UUID(), name: "Guacamole", amount: "100", unit: "g")], steps: ["Preheat oven to 180°C.", "Spread chips on baking tray.", "Cover with grated cheese.", "Add jalapeños on top.", "Bake 8-10 minutes until cheese melts.", "Top with sour cream, salsa and guacamole."], reviews: [], isFavorite: false),

        // SOUP
        Recipe(id: UUID(), name: "Chicken Soup", description: "Hearty and comforting homemade chicken soup with vegetables.", category: "Soup", imageName: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=80", prepTime: 20, cookTime: 60, servings: 6, calories: 280, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Whole chicken", amount: "1", unit: "kg"), Ingredient(id: UUID(), name: "Carrots", amount: "3", unit: "pcs"), Ingredient(id: UUID(), name: "Celery", amount: "3", unit: "stalks"), Ingredient(id: UUID(), name: "Onion", amount: "1", unit: "large"), Ingredient(id: UUID(), name: "Egg noodles", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Fresh parsley", amount: "handful", unit: "")], steps: ["Place chicken in pot, cover with water.", "Bring to boil, skim foam.", "Add vegetables, simmer 45 minutes.", "Remove chicken, shred meat.", "Add noodles, cook 8 minutes.", "Return chicken, season with parsley."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "French Onion Soup", description: "Rich caramelized onion soup topped with gruyère-covered croutons.", category: "Soup", imageName: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&q=80", prepTime: 15, cookTime: 60, servings: 4, calories: 380, difficulty: .medium, ingredients: [Ingredient(id: UUID(), name: "Yellow onions", amount: "6", unit: "large"), Ingredient(id: UUID(), name: "Beef stock", amount: "1.5", unit: "L"), Ingredient(id: UUID(), name: "Gruyère cheese", amount: "200", unit: "g"), Ingredient(id: UUID(), name: "Baguette", amount: "1", unit: "pcs"), Ingredient(id: UUID(), name: "Butter", amount: "60", unit: "g"), Ingredient(id: UUID(), name: "White wine", amount: "150", unit: "ml")], steps: ["Slowly caramelize onions in butter 45 min.", "Add wine, reduce by half.", "Add beef stock, simmer 15 minutes.", "Season with salt and pepper.", "Ladle into oven-safe bowls.", "Top with baguette slice and cheese, broil."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Tomato Basil Soup", description: "Velvety roasted tomato soup with fresh basil and a swirl of cream.", category: "Soup", imageName: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&q=80", prepTime: 15, cookTime: 40, servings: 4, calories: 220, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Tomatoes", amount: "1", unit: "kg"), Ingredient(id: UUID(), name: "Vegetable stock", amount: "500", unit: "ml"), Ingredient(id: UUID(), name: "Heavy cream", amount: "100", unit: "ml"), Ingredient(id: UUID(), name: "Fresh basil", amount: "handful", unit: ""), Ingredient(id: UUID(), name: "Garlic", amount: "4", unit: "cloves"), Ingredient(id: UUID(), name: "Olive oil", amount: "3", unit: "tbsp")], steps: ["Roast tomatoes and garlic with olive oil.", "Transfer to pot with stock.", "Simmer 20 minutes.", "Blend until smooth.", "Stir in cream.", "Garnish with basil and serve."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Minestrone", description: "Hearty Italian vegetable soup with pasta, beans and seasonal vegetables.", category: "Soup", imageName: "https://images.unsplash.com/photo-1604152135912-04a022e23696?w=400&q=80", prepTime: 20, cookTime: 40, servings: 6, calories: 260, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Mixed vegetables", amount: "500", unit: "g"), Ingredient(id: UUID(), name: "Cannellini beans", amount: "400", unit: "g"), Ingredient(id: UUID(), name: "Small pasta", amount: "150", unit: "g"), Ingredient(id: UUID(), name: "Tomato passata", amount: "400", unit: "g"), Ingredient(id: UUID(), name: "Vegetable stock", amount: "1", unit: "L"), Ingredient(id: UUID(), name: "Parmesan rind", amount: "1", unit: "pcs")], steps: ["Sauté onions, carrots and celery.", "Add vegetables and tomatoes.", "Pour in stock and parmesan rind.", "Simmer 20 minutes.", "Add pasta and beans.", "Cook 10 more minutes, serve with parmesan."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Lentil Soup", description: "Warming red lentil soup with cumin, turmeric and a squeeze of lemon.", category: "Soup", imageName: "https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?w=400&q=80", prepTime: 10, cookTime: 30, servings: 4, calories: 290, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Red lentils", amount: "300", unit: "g"), Ingredient(id: UUID(), name: "Vegetable stock", amount: "1", unit: "L"), Ingredient(id: UUID(), name: "Cumin", amount: "2", unit: "tsp"), Ingredient(id: UUID(), name: "Turmeric", amount: "1", unit: "tsp"), Ingredient(id: UUID(), name: "Lemon juice", amount: "3", unit: "tbsp"), Ingredient(id: UUID(), name: "Onion", amount: "1", unit: "large")], steps: ["Sauté onion until soft.", "Add spices, toast 1 minute.", "Add rinsed lentils and stock.", "Simmer 25 minutes until tender.", "Blend partially for texture.", "Add lemon juice and season."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Gazpacho", description: "Chilled Spanish tomato soup with cucumber, pepper and olive oil.", category: "Soup", imageName: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=80", prepTime: 20, cookTime: 0, servings: 4, calories: 140, difficulty: .easy, ingredients: [Ingredient(id: UUID(), name: "Ripe tomatoes", amount: "800", unit: "g"), Ingredient(id: UUID(), name: "Cucumber", amount: "1", unit: "large"), Ingredient(id: UUID(), name: "Red pepper", amount: "1", unit: "pcs"), Ingredient(id: UUID(), name: "Garlic", amount: "2", unit: "cloves"), Ingredient(id: UUID(), name: "Olive oil", amount: "60", unit: "ml"), Ingredient(id: UUID(), name: "Sherry vinegar", amount: "3", unit: "tbsp")], steps: ["Chop all vegetables roughly.", "Blend tomatoes, cucumber and pepper.", "Add garlic, olive oil and vinegar.", "Season with salt.", "Strain for smooth texture.", "Chill for at least 2 hours."], reviews: [], isFavorite: false),

        Recipe(id: UUID(), name: "Pho", description: "Vietnamese beef noodle soup with aromatic broth, herbs and bean sprouts.", category: "Soup", imageName: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&q=80", prepTime: 30, cookTime: 180, servings: 4, calories: 420, difficulty: .hard, ingredients: [Ingredient(id: UUID(), name: "Beef bones", amount: "1", unit: "kg"), Ingredient(id: UUID(), name: "Rice noodles", amount: "400", unit: "g"), Ingredient(id: UUID(), name: "Beef sirloin", amount: "300", unit: "g"), Ingredient(id: UUID(), name: "Star anise", amount: "4", unit: "pcs"), Ingredient(id: UUID(), name: "Cinnamon stick", amount: "1", unit: "pcs"), Ingredient(id: UUID(), name: "Bean sprouts", amount: "200", unit: "g")], steps: ["Char onion and ginger.", "Simmer bones with spices 3 hours.", "Strain and season broth.", "Cook noodles, place in bowls.", "Add raw sliced beef to noodles.", "Pour hot broth over to cook beef.", "Top with herbs and bean sprouts."], reviews: [], isFavorite: false),
    ]
}
